// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bbs-example-server": home Resource Client
//
// Command:
// $ goagen
// --design=BBS-Example/api/bbs-example-server/design
// --out=$(GOPATH)/src/BBS-Example/api/bbs-example-server
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// HomeHomePath computes a request path to the home action of home.
func HomeHomePath() string {

	return fmt.Sprintf("/home")
}

// home.
func (c *Client) HomeHome(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewHomeHomeRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewHomeHomeRequest create the request corresponding to the home action endpoint of the home resource.
func (c *Client) NewHomeHomeRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
