// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bbs-example-server": ping Resource Client
//
// Command:
// $ goagen
// --design=BBS-Example/api/bbs-example-server/design
// --out=$(GOPATH)/src/BBS-Example/api/bbs-example-server
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// PingPingPath computes a request path to the ping action of ping.
func PingPingPath() string {

	return fmt.Sprintf("/ping")
}

// PingPong.
func (c *Client) PingPing(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewPingPingRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewPingPingRequest create the request corresponding to the ping action endpoint of the ping resource.
func (c *Client) NewPingPingRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
