// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bbs-example-server": user_post Resource Client
//
// Command:
// $ goagen
// --design=BBS-Example/api/bbs-example-server/design
// --out=$(GOPATH)/src/BBS-Example/api/bbs-example-server
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// CreateUserPostPath computes a request path to the create action of user_post.
func CreateUserPostPath() string {

	return fmt.Sprintf("/user_posts/")
}

// Create user post.
func (c *Client) CreateUserPost(ctx context.Context, path string, payload *UserPostPayload, contentType string) (*http.Response, error) {
	req, err := c.NewCreateUserPostRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewCreateUserPostRequest create the request corresponding to the create action endpoint of the user_post resource.
func (c *Client) NewCreateUserPostRequest(ctx context.Context, path string, payload *UserPostPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("POST", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}

// IndexUserPostPath computes a request path to the index action of user_post.
func IndexUserPostPath() string {

	return fmt.Sprintf("/user_posts/")
}

// Fetch user posts.
func (c *Client) IndexUserPost(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewIndexUserPostRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewIndexUserPostRequest create the request corresponding to the index action endpoint of the user_post resource.
func (c *Client) NewIndexUserPostRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
