// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "bbs-example-server": Application Contexts
//
// Command:
// $ goagen
// --design=BBS-Example/api/bbs-example-server/design
// --out=$(GOPATH)/src/BBS-Example/api/bbs-example-server
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// HomeHomeContext provides the home home action context.
type HomeHomeContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewHomeHomeContext parses the incoming request URL and body, performs validations and creates the
// context used by the home controller home action.
func NewHomeHomeContext(ctx context.Context, r *http.Request, service *goa.Service) (*HomeHomeContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := HomeHomeContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *HomeHomeContext) OK(r *JSON) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "application/json")
	}
	return ctx.ResponseData.Service.Send(ctx.Context, 200, r)
}

// PingPingContext provides the ping ping action context.
type PingPingContext struct {
	context.Context
	*goa.ResponseData
	*goa.RequestData
}

// NewPingPingContext parses the incoming request URL and body, performs validations and creates the
// context used by the ping controller ping action.
func NewPingPingContext(ctx context.Context, r *http.Request, service *goa.Service) (*PingPingContext, error) {
	var err error
	resp := goa.ContextResponse(ctx)
	resp.Service = service
	req := goa.ContextRequest(ctx)
	req.Request = r
	rctx := PingPingContext{Context: ctx, ResponseData: resp, RequestData: req}
	return &rctx, err
}

// OK sends a HTTP response with status code 200.
func (ctx *PingPingContext) OK(resp []byte) error {
	if ctx.ResponseData.Header().Get("Content-Type") == "" {
		ctx.ResponseData.Header().Set("Content-Type", "text/plain")
	}
	ctx.ResponseData.WriteHeader(200)
	_, err := ctx.ResponseData.Write(resp)
	return err
}
